apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-extension-app
  namespace: retail-%userid%
spec:
  destination:
    namespace: argocd-%userid%
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/bgd/overlays/rollouts-demo
    repoURL: https://github.com/kkphil83/openshift-gitops-examples
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true