---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rollout-extension
  name: rollout-extension
spec:
  replicas: 0
  selector:
    matchLabels:
      app: rollout-extension
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rollout-extension
    spec:
      containers:
      - name: rollout-extension
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
---
