---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rollouts-extension
  name: rollouts-extension
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rollouts-extension
---